/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.ButtonGroup;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author abelc
 */
public class ConfigurarPartidaFrm extends javax.swing.JFrame {

    /**
     * Creates new form ConfigurarPartidaFrm
     */
    public ConfigurarPartidaFrm() {
        initComponents();
        jugadorRadioButton2.setSelected(true);
        fichaRadioButton2.setSelected(true);
        ButtonGroup grupoJugadores = new ButtonGroup();
        ButtonGroup grupoFichas = new ButtonGroup();
        grupoJugadores.add(jugadorRadioButton2);
        grupoJugadores.add(jugadorRadioButton3);
        grupoJugadores.add(jugadorRadioButton4);

        grupoFichas.add(fichaRadioButton2);
        grupoFichas.add(fichaRadioButton4);
        grupoFichas.add(fichaRadioButton6);
        SpinnerNumberModel fondoModel = new SpinnerNumberModel(0, 0, null, 100);
        jSpinner2.setModel(fondoModel);
        jSpinner2.setEditor(new JSpinner.NumberEditor(jSpinner2, "#"));
        SpinnerNumberModel cantidadModel = new SpinnerNumberModel(0, 0, null, 50);
        jSpinner1.setModel(cantidadModel);
        jSpinner1.setEditor(new JSpinner.NumberEditor(jSpinner1, "#"));
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jugadorRadioButton2 = new javax.swing.JRadioButton();
        jugadorRadioButton3 = new javax.swing.JRadioButton();
        jugadorRadioButton4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        fichaRadioButton2 = new javax.swing.JRadioButton();
        fichaRadioButton4 = new javax.swing.JRadioButton();
        fichaRadioButton6 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        btnCrearPartida = new javax.swing.JButton();
        btnCrearPartida1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar Partida");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setBackground(new java.awt.Color(221, 209, 121));
        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(213, 198, 86));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONFIGURA TU PARTIDA");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 100));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APUESTAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 700, 40));

        jugadorRadioButton2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jugadorRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jugadorRadioButton2.setText("2 jugadores");
        jugadorRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadorRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jugadorRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 130, -1));

        jugadorRadioButton3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jugadorRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jugadorRadioButton3.setText("3 jugadores");
        jugadorRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadorRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jugadorRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jugadorRadioButton4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jugadorRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jugadorRadioButton4.setText("4 jugadores");
        jPanel2.add(jugadorRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("JUGADORES");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        fichaRadioButton2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        fichaRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        fichaRadioButton2.setText("2 Fichas");
        jPanel2.add(fichaRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 90, -1));

        fichaRadioButton4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        fichaRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        fichaRadioButton4.setText("4 fichas");
        jPanel2.add(fichaRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        fichaRadioButton6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        fichaRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        fichaRadioButton6.setText("6 fichas");
        jPanel2.add(fichaRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 100, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FICHAS");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 119, 700, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad a pagar:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jSpinner1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 110, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fondo de apuesta:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jSpinner2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jSpinner2.setToolTipText("");
        jSpinner2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 110, -1));

        btnCrearPartida.setBackground(new java.awt.Color(213, 198, 86));
        btnCrearPartida.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        btnCrearPartida.setText("Crear partida");
        btnCrearPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 170, 40));

        btnCrearPartida1.setBackground(new java.awt.Color(213, 198, 86));
        btnCrearPartida1.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        btnCrearPartida1.setText("Regresar");
        btnCrearPartida1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearPartida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartida1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrearPartida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 160, 40));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 700, 40));

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 700, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    private void jugadorRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadorRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugadorRadioButton3ActionPerformed

    private void jugadorRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadorRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugadorRadioButton2ActionPerformed

    private void btnCrearPartida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPartida1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigurarPartidaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigurarPartidaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigurarPartidaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigurarPartidaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigurarPartidaFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnCrearPartida1;
    private javax.swing.JRadioButton fichaRadioButton2;
    private javax.swing.JRadioButton fichaRadioButton4;
    private javax.swing.JRadioButton fichaRadioButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JRadioButton jugadorRadioButton2;
    private javax.swing.JRadioButton jugadorRadioButton3;
    private javax.swing.JRadioButton jugadorRadioButton4;
    // End of variables declaration//GEN-END:variables
}
